//! Reading `.mdl` — the studio model header.
//!
//! `studiohdr_t` and the body-part/model/mesh hierarchy under it
//! (`public/studio.h:2532`). This reads the parts a static prop needs: the
//! hierarchy, the material table, the bounds and the flags. It does not read
//! bones beyond counting them, animations, sequences, hitboxes, attachments,
//! eyeballs, flexes or IK — `studio.h` is 3,926 lines and a prop reaches
//! almost none of it.
//!
//! # Every offset is relative to its own struct
//!
//! `mstudiobodyparts_t::modelindex` is measured from the body part, and
//! `mstudiomesh_t`'s offsets from the mesh — which is what all of `studio.h`'s
//! `(byte *)this + index` accessors encode. Valve kept the file mapped and
//! chased those pointers; this resolves every offset once, at parse time, into
//! owned `Vec`s. That is the same trade `world::bsp` made, for the same reason:
//! it is what most of the C++'s lifetime management exists to support.

use super::StudioError;
use glam::Vec3;

/// `"IDST"`, little-endian. `studio.h:2461`.
const IDENT: u32 = u32::from_le_bytes(*b"IDST");

/// `STUDIO_VERSION`, `studio.h:63`. Every one of the 2,041 models Portal 2
/// ships is this version, so there is nothing to branch on.
const VERSION: i32 = 49;

/// `sizeof(studiohdr_t)` is much larger, but this is everything up to and
/// including `bodypartindex` at 236 — the last field this reader needs.
const MIN_HEADER: usize = 240;

/// `sizeof(mstudiobodyparts_t)`, `studio.h:1985`.
const BODY_PART_STRIDE: usize = 16;

/// `sizeof(mstudiomodel_t)`, `studio.h:1673`. 108 bytes of fields, then a
/// 12-byte `mstudio_modelvertexdata_t` (three naked pointers) and `unused[7]`.
/// On 64-bit those become 24 and `unused[4]`, which is why the total is 148
/// either way — the struct is deliberately the same size in both builds.
pub(super) const MODEL_STRIDE: usize = 148;

/// `sizeof(mstudiomesh_t)`, `studio.h:1634`. 48 bytes of fields, a 44-byte
/// `mstudio_meshvertexdata_t`, then `unused[6]`.
///
/// The 44 is the one that is easy to get wrong: it ends in a
/// `serializedstudioptr_t`, which is **always 8 bytes** — a pointer plus
/// explicit padding on 32-bit — precisely so that a struct containing one has
/// the same size in both builds (`studio.h:118`). Reading it as a 4-byte
/// pointer makes the stride 112 and every mesh after the first garbage.
pub(super) const MESH_STRIDE: usize = 116;

/// `sizeof(mstudiotexture_t)`, `studio.h:1463`.
const TEXTURE_STRIDE: usize = 64;

/// `sizeof(mstudiovertex_t)`, `studio.h:1447` — and the header says so in a
/// comment, because it matters. Used here to convert
/// `mstudiomodel_t::vertexindex`, which is a **byte** offset.
const VERTEX_STRIDE: i32 = 48;

/// `sizeof(Vector4D)` — the stride of the `.vvd`'s tangent array, and the
/// divisor for `mstudiomodel_t::tangentsindex`.
const TANGENT_STRIDE: i32 = 16;

/// `studiohdr_t::flags`. The subset a static prop can carry; the full set is in
/// `studio.h:2380` onwards.
///
/// A newtype rather than `bitflags!`, matching
/// [`TextureFlags`](crate::materials::vtf::TextureFlags): the set is fixed by
/// the file format and the operations needed are containment and equality.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct StudioFlags(pub u32);

#[allow(dead_code)]
impl StudioFlags {
    /// `STUDIOHDR_FLAGS_AUTOGENERATED_HITBOX`. Set on all 968 of Portal 2's
    /// static prop models — the compiler makes a hitbox when the `.qc` does
    /// not.
    pub const AUTOGENERATED_HITBOX: Self = Self(1 << 0);
    /// Set at *load* time by the original, not by the compiler, which is why
    /// it reads as clear in every shipped file.
    pub const USES_ENV_CUBEMAP: Self = Self(1 << 1);
    pub const FORCE_OPAQUE: Self = Self(1 << 2);
    /// Opaque parts in the opaque pass, translucent parts in the translucent
    /// pass. 38 of the 968 set this, and this port has no sorted translucent
    /// pass yet — see `portdocs/STUDIO.md` §9.
    pub const TRANSLUCENT_TWOPASS: Self = Self(1 << 3);
    /// `STUDIOHDR_FLAGS_STATIC_PROP`. Valve's own marker, set on all 968.
    pub const STATIC_PROP: Self = Self(1 << 4);
    pub const USES_FB_TEXTURE: Self = Self(1 << 5);
    pub const HASSHADOWLOD: Self = Self(1 << 6);
    pub const USES_BUMPMAPPING: Self = Self(1 << 7);
    pub const USE_SHADOWLOD_MATERIALS: Self = Self(1 << 8);
    pub const OBSOLETE: Self = Self(1 << 9);
    pub const NO_FORCED_FADE: Self = Self(1 << 11);
    pub const AMBIENT_BOOST: Self = Self(1 << 16);
    pub const DO_NOT_CAST_SHADOWS: Self = Self(1 << 17);
    pub const CAST_TEXTURE_SHADOWS: Self = Self(1 << 18);

    pub fn contains(self, other: Self) -> bool {
        self.0 & other.0 == other.0
    }
}

/// One mesh: a contiguous run of the model's vertices, all wearing one material.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Mesh {
    /// Index into [`Mdl::textures`].
    pub material: usize,
    /// `vertexoffset` — this mesh's first vertex **within its model**, which is
    /// the base the `.vtx`'s `origMeshVertID` is measured from.
    pub vertex_offset: u32,
    pub vertex_count: u32,
}

/// One model — a group of meshes sharing a slice of the vertex pool.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Model {
    pub name: String,
    /// The model's first vertex in the `.vvd` pool, **as a vertex index**.
    ///
    /// `mstudiomodel_t::vertexindex` is a *byte* offset — `GetGlobalVertexIndex`
    /// (`studio.h:1737`) divides it by `sizeof(mstudiovertex_t)`. Storing the
    /// divided value here means no caller can forget to.
    pub vertex_index: u32,
    /// Likewise `tangentsindex / sizeof(Vector4D)`. Equal to
    /// [`vertex_index`](Model::vertex_index) in every shipped file, but they
    /// are separate arrays with separate strides and the format does not
    /// promise it.
    pub tangent_index: u32,
    pub vertex_count: u32,
    pub meshes: Vec<Mesh>,
}

/// One body part — a set of interchangeable models.
///
/// Body groups let a model swap parts (a character's head, say). Every one of
/// Portal 2's static prop body parts contains exactly one model, so the choice
/// is never exercised here, but the level of nesting is in the format and the
/// `.vtx` mirrors it exactly.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BodyPart {
    pub name: String,
    pub models: Vec<Model>,
}

/// A parsed `.mdl`.
#[derive(Debug, Clone)]
pub struct Mdl {
    pub path: String,
    /// `studiohdr_t::name` — recorded by the compiler, not necessarily the
    /// path the file ships at.
    pub name: String,
    pub checksum: u32,
    pub flags: StudioFlags,
    pub bounds: (Vec3, Vec3),
    pub illum_position: Vec3,
    pub bone_count: u32,
    /// `mstudiotexture_t` names, in order — what a mesh's `material` indexes.
    /// These are *bare* names with no directory: `pillar_64` and not
    /// `models/props_bts/pillar_64`.
    pub textures: Vec<String>,
    /// `cdtextureindex` — the directories to try, in order, each already
    /// slash-normalized, lowercased and terminated with `/`.
    pub texture_dirs: Vec<String>,
    pub body_parts: Vec<BodyPart>,
}

impl Mdl {
    /// Parses a `.mdl`.
    pub fn parse(path: String, bytes: &[u8]) -> Result<Mdl, StudioError> {
        let r = Reader {
            path: &path,
            what: "a .mdl",
            bytes,
        };

        if bytes.len() < MIN_HEADER {
            return Err(StudioError::TooShort {
                path,
                what: "a studio header",
                size: bytes.len(),
                needed: MIN_HEADER,
            });
        }

        let ident = r.u32(0)?;
        if ident != IDENT {
            return Err(StudioError::BadIdent {
                path,
                what: ".mdl",
                ident,
                expected: IDENT,
            });
        }
        let version = r.i32(4)?;
        if version != VERSION {
            return Err(StudioError::Version {
                path,
                what: ".mdl",
                version,
                expected: VERSION,
            });
        }

        let checksum = r.u32(8)?;
        let name = r.fixed_string(12, 64);
        let illum_position = r.vec3(92)?;
        let bounds = (r.vec3(128)?, r.vec3(140)?);
        let flags = StudioFlags(r.u32(152)?);
        let bone_count = r.i32(156)?.max(0) as u32;

        let textures = {
            let count = r.count(204, "textures")?;
            let base = r.offset(208, "textureindex")?;
            let mut names = Vec::with_capacity(count);
            for i in 0..count {
                let at = base + i * TEXTURE_STRIDE;
                let name_at = r.relative_offset(at, at, "mstudiotexture_t::sznameindex")?;
                names.push(normalize(&r.c_string(name_at)?));
            }
            names
        };

        let texture_dirs = {
            let count = r.count(212, "cdtextures")?;
            let base = r.offset(216, "cdtextureindex")?;
            let mut dirs = Vec::with_capacity(count);
            for i in 0..count {
                // The cdtexture table is an array of *offsets*, each measured
                // from the start of the file rather than from the table — the
                // one place in the format that is not struct-relative
                // (`studio.h:2676`: `(char *)this + *((int *)((byte *)this + cdtextureindex) + i)`,
                // and `this` is the header, which is the file).
                let at = r.offset(base + i * 4, "cdtexture entry")?;
                let dir = normalize(&r.c_string(at)?);
                dirs.push(if dir.ends_with('/') || dir.is_empty() {
                    dir
                } else {
                    format!("{dir}/")
                });
            }
            dirs
        };

        let body_parts = {
            let count = r.count(232, "body parts")?;
            let base = r.offset(236, "bodypartindex")?;
            let mut parts = Vec::with_capacity(count);
            for i in 0..count {
                parts.push(Self::body_part(&r, base + i * BODY_PART_STRIDE, textures.len())?);
            }
            parts
        };

        Ok(Mdl {
            path,
            name: normalize(&name),
            checksum,
            flags,
            bounds,
            illum_position,
            bone_count,
            textures,
            texture_dirs,
            body_parts,
        })
    }

    fn body_part(r: &Reader, at: usize, texture_count: usize) -> Result<BodyPart, StudioError> {
        let name_at = r.relative_offset(at, at, "mstudiobodyparts_t::sznameindex")?;
        let name = normalize(&r.c_string(name_at)?);
        let count = r.count(at + 4, "models")?;
        let base = r.relative_offset(at + 12, at, "mstudiobodyparts_t::modelindex")?;

        let mut models = Vec::with_capacity(count);
        for i in 0..count {
            models.push(Self::model(r, base + i * MODEL_STRIDE, texture_count)?);
        }
        Ok(BodyPart { name, models })
    }

    fn model(r: &Reader, at: usize, texture_count: usize) -> Result<Model, StudioError> {
        let name = normalize(&r.fixed_string(at, 64));
        let mesh_count = r.count(at + 72, "meshes")?;
        let mesh_base = r.relative_offset(at + 76, at, "mstudiomodel_t::meshindex")?;
        let vertex_count = r.i32(at + 80)?.max(0) as u32;

        // Both are byte offsets into the .vvd's arrays, not indices. A file
        // whose offset is not a whole number of records is corrupt in a way
        // that would otherwise silently shear every vertex in the model.
        let vertex_index = r.i32(at + 84)?;
        let tangent_index = r.i32(at + 88)?;
        for (value, stride, what) in [
            (vertex_index, VERTEX_STRIDE, "vertexindex"),
            (tangent_index, TANGENT_STRIDE, "tangentsindex"),
        ] {
            if value < 0 || value % stride != 0 {
                return Err(r.corrupt(format!(
                    "model {name:?} has {what} {value}, which is not a multiple of {stride}"
                )));
            }
        }

        let mut meshes = Vec::with_capacity(mesh_count);
        for i in 0..mesh_count {
            let mesh_at = mesh_base + i * MESH_STRIDE;
            let material = r.i32(mesh_at)?;
            if material < 0 || material as usize >= texture_count {
                return Err(r.corrupt(format!(
                    "mesh {i} of model {name:?} names material {material} of {texture_count}"
                )));
            }
            let mesh_vertex_count = r.i32(mesh_at + 8)?.max(0) as u32;
            let vertex_offset = r.i32(mesh_at + 12)?;
            if vertex_offset < 0 || vertex_offset as u32 + mesh_vertex_count > vertex_count {
                return Err(r.corrupt(format!(
                    "mesh {i} of model {name:?} covers vertices {vertex_offset}..{} of {vertex_count}",
                    vertex_offset as i64 + mesh_vertex_count as i64
                )));
            }
            meshes.push(Mesh {
                material: material as usize,
                vertex_offset: vertex_offset as u32,
                vertex_count: mesh_vertex_count,
            });
        }

        Ok(Model {
            name,
            vertex_index: (vertex_index / VERTEX_STRIDE) as u32,
            tangent_index: (tangent_index / TANGENT_STRIDE) as u32,
            vertex_count,
            meshes,
        })
    }

    /// The material paths to try for texture `index`, in the order the format
    /// wants them tried.
    ///
    /// Material resolution is a cross product, not a filesystem search: for
    /// each `cdtexture` directory in order, `<dir><texture name>`. The first
    /// that exists as `materials/<candidate>.vmt` wins
    /// (`studiorender/studiorender.cpp`'s `FindMaterial`). A model with no
    /// `cdtextures` at all falls back to the bare name.
    ///
    /// Returned as candidates rather than resolved here so that this module
    /// needs no `Vfs` — see [`assemble`](super::assemble).
    pub fn material_candidates(&self, index: usize) -> Vec<String> {
        let Some(name) = self.textures.get(index) else {
            return Vec::new();
        };
        // An absolute-looking name ignores the directories, as `Q_IsAbsolutePath`
        // does in the original.
        if self.texture_dirs.is_empty() {
            return vec![name.clone()];
        }
        self.texture_dirs
            .iter()
            .map(|dir| format!("{dir}{name}"))
            .collect()
    }

    /// Total vertices across every body part and model — what the `.vvd` must
    /// be able to supply.
    pub fn vertex_count(&self) -> u32 {
        self.body_parts
            .iter()
            .flat_map(|part| &part.models)
            .map(|model| model.vertex_count)
            .sum()
    }
}

/// Lowercases and forward-slashes a name out of the file, the way every Valve
/// path comparison does.
fn normalize(name: &str) -> String {
    name.replace('\\', "/").to_ascii_lowercase()
}

/// Bounds-checked little-endian reads over one file.
///
/// Every accessor returns a `Corrupt` naming the offset rather than panicking:
/// a `.mdl` can arrive in a downloaded map, so it is untrusted input, and the
/// same reasoning `world::bsp::validate` records applies here.
pub(super) struct Reader<'a> {
    pub path: &'a str,
    pub what: &'static str,
    pub bytes: &'a [u8],
}

impl Reader<'_> {
    pub fn corrupt(&self, what: String) -> StudioError {
        StudioError::Corrupt {
            path: self.path.to_owned(),
            what,
        }
    }

    fn bytes_at(&self, at: usize, len: usize) -> Result<&[u8], StudioError> {
        self.bytes.get(at..at + len).ok_or_else(|| {
            self.corrupt(format!(
                "{} bytes at {at} run past the end of {} ({} bytes)",
                len,
                self.what,
                self.bytes.len()
            ))
        })
    }

    pub fn i32(&self, at: usize) -> Result<i32, StudioError> {
        Ok(i32::from_le_bytes(
            self.bytes_at(at, 4)?.try_into().expect("4 bytes"),
        ))
    }

    pub fn u32(&self, at: usize) -> Result<u32, StudioError> {
        Ok(self.i32(at)? as u32)
    }

    pub fn f32(&self, at: usize) -> Result<f32, StudioError> {
        Ok(f32::from_le_bytes(
            self.bytes_at(at, 4)?.try_into().expect("4 bytes"),
        ))
    }

    pub fn u16(&self, at: usize) -> Result<u16, StudioError> {
        Ok(u16::from_le_bytes(
            self.bytes_at(at, 2)?.try_into().expect("2 bytes"),
        ))
    }

    pub fn vec3(&self, at: usize) -> Result<Vec3, StudioError> {
        Ok(Vec3::new(
            self.f32(at)?,
            self.f32(at + 4)?,
            self.f32(at + 8)?,
        ))
    }

    /// A count field, refused if negative or absurd enough to be a misread
    /// offset rather than a count.
    pub fn count(&self, at: usize, what: &str) -> Result<usize, StudioError> {
        let n = self.i32(at)?;
        if n < 0 || n as usize > self.bytes.len() {
            return Err(self.corrupt(format!("{what} count is {n}")));
        }
        Ok(n as usize)
    }

    /// An offset measured from the start of the file.
    pub fn offset(&self, at: usize, what: &str) -> Result<usize, StudioError> {
        let value = self.i32(at)?;
        if value < 0 || value as usize > self.bytes.len() {
            return Err(self.corrupt(format!("{what} is {value}")));
        }
        Ok(value as usize)
    }

    /// An offset measured from `base`, which is how nearly every index inside
    /// a `.mdl` or `.vtx` is expressed.
    pub fn relative_offset(
        &self,
        at: usize,
        base: usize,
        what: &str,
    ) -> Result<usize, StudioError> {
        let value = self.i32(at)?;
        let resolved = base as i64 + value as i64;
        if resolved < 0 || resolved as usize > self.bytes.len() {
            return Err(self.corrupt(format!("{what} is {value} relative to {base}")));
        }
        Ok(resolved as usize)
    }

    /// A fixed-width, NUL-padded field such as `studiohdr_t::name[64]`.
    pub fn fixed_string(&self, at: usize, len: usize) -> String {
        let raw = self.bytes.get(at..at + len).unwrap_or_default();
        let end = raw.iter().position(|&b| b == 0).unwrap_or(raw.len());
        String::from_utf8_lossy(&raw[..end]).into_owned()
    }

    /// A NUL-terminated string at `at`.
    pub fn c_string(&self, at: usize) -> Result<String, StudioError> {
        let rest = self
            .bytes
            .get(at..)
            .ok_or_else(|| self.corrupt(format!("string offset {at} is past the end")))?;
        let end = rest
            .iter()
            .position(|&b| b == 0)
            .ok_or_else(|| self.corrupt(format!("string at {at} is not terminated")))?;
        Ok(String::from_utf8_lossy(&rest[..end]).into_owned())
    }
}
